title: "Elfried KINZOUN S.D"
description: "Portfolio de projets hebdomadaires en vision par ordinateur et IA."
<<<<<<< HEAD
logo: cayman/assets/images/im1.jpeg
theme: cayman
=======
theme: jekyll-theme-minimal
>>>>>>> origin/main

author:
  name: "Elfried Steve David KINZOUN"
  email: "ekfriedkinzoun@gmail.com"
  description: "Je suis passionné par la robotique et l'intelligence artificielle. Je suis Béninois."

show_excerpts: true
paginate: 5

social:
  github: "https://github.com/elfried96"
  linkedin: "https://linkedin.com/in/tonpseudo"
  twitter: "https://twitter.com/tonpseudo"

plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge
